ovs: add internal interface example
nmstate/nmstate.github.io pull request #22
Opened 2019-10-15 22:13 UTC by phoracek

Add an example of OVS internal interface. Having no system interface
and no IP may make OVS difficult to grasp for ovs-vsctl users.

Also drop default OVS bridge options from basic examples. Simpler is
better. Let's not lose users on first sight.

Signed-off-by: Petr Horacek <phoracek@redhat.com>

2019-10-15 22:13 UTC, phoracek commented
@cathay4t @EdDev please take a look

2019-10-18 14:50 UTC, phoracek commented
@tyll would you please take a look?

2019-10-22 17:00 UTC, EdDev commented
I think it is great to have such an example, but the design document may not be the correct place for this. We have not maintained the design document with updates. It is placed here as a reference for the starting point of the project and includes its original motivation.

We have other places we keep examples, like: https://github.com/nmstate/nmstate.github.io/blob/master/examples.md

Will the examples document fit?

2019-10-22 17:04 UTC, phoracek commented
@EdDev this PR adds it to examples as well. Let me just drop it from the API document.

2019-10-22 17:06 UTC, phoracek commented
@EdDev please take another look. I also dropped those random default options to make the example more appealing, but feel free to comment on it.

2019-10-24 21:00 UTC, EdDev requested changes
I'm good with the approach, thank you.
The text needs a bit of rephrasing.

2019-10-24 21:00 UTC, EdDev commented on examples.md
> +and it can be used for IPv4/IPv6 configuration.
It is hard to read, could you please rephrase?
Maybe use something like `... a bridge with a system (eth3) and an internal (ovs0)...`

2019-10-25 12:58 UTC, phoracek commented on examples.md
> +and it can be used for IPv4/IPv6 configuration.
Is it better now?

2019-10-25 18:26 UTC, EdDev approved these changes
Thank you!

2019-10-25 18:28 UTC, merged