Add Team interface support documentation
nmstate/nmstate.github.io pull request #33
Opened 2020-02-20 12:47 UTC by ffmancera

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

2020-02-20 16:50 UTC, tyll commented on examples.md
> +- name: team
Please call this `team0`

2020-02-20 19:41 UTC, ffmancera commented on examples.md
> +- name: team
Ops, done. Thanks!

2020-02-28 13:38 UTC, ffmancera commented
@tyll could we merge this? :-)

2020-03-03 12:29 UTC, cathay4t requested changes

2020-03-03 12:29 UTC, cathay4t commented on devel/api.md
> +refer to [teamd manual page](https://www.mankier.com/5/teamd.conf)
I would not suggest to use external third party website for manpage, you may just say ` man 5 tead.conf` or the upstream link
of that manpage: https://github.com/jpirko/libteam/blob/master/man/teamd.conf.5

2020-08-05 11:09 UTC, closed without merging